//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanCode.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanCode.Resources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum declarations per method.
        /// </summary>
        public static string DeclarationsMaximum {
            get {
                return ResourceManager.GetString("DeclarationsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum chained references.
        /// </summary>
        public static string MaximumChainedReferences {
            get {
                return ResourceManager.GetString("MaximumChainedReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum interface dependencies for a constructor.
        /// </summary>
        public static string MaximumConstructorDependencies {
            get {
                return ResourceManager.GetString("MaximumConstructorDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum expressions inside a condition.
        /// </summary>
        public static string MaximumExpressionsInsideACondition {
            get {
                return ResourceManager.GetString("MaximumExpressionsInsideACondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum level of nesting in a method.
        /// </summary>
        public static string MaximumLevelOfNestingInAMethod {
            get {
                return ResourceManager.GetString("MaximumLevelOfNestingInAMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum method declaration parameters.
        /// </summary>
        public static string MaximumMethodDeclarationParameters {
            get {
                return ResourceManager.GetString("MaximumMethodDeclarationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum methods per class.
        /// </summary>
        public static string MaximumMethodsPerClass {
            get {
                return ResourceManager.GetString("MaximumMethodsPerClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum statements per method.
        /// </summary>
        public static string MaximumStatementsPerMethod {
            get {
                return ResourceManager.GetString("MaximumStatementsPerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of meaningless suffixes.
        /// </summary>
        public static string MeaninglessNameSuffixes {
            get {
                return ResourceManager.GetString("MeaninglessNameSuffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate items with commas.
        /// </summary>
        public static string MeaninglessNameSuffixesTooltip {
            get {
                return ResourceManager.GetString("MeaninglessNameSuffixesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum method name length.
        /// </summary>
        public static string MinimumMethodNameLength {
            get {
                return ResourceManager.GetString("MinimumMethodNameLength", resourceCulture);
            }
        }
    }
}
