//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanCode.Resources {
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanCode.Resources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum declarations per method ähnelt.
        /// </summary>
        internal static string DeclarationsMaximum {
            get {
                return ResourceManager.GetString("DeclarationsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum chained references ähnelt.
        /// </summary>
        internal static string MaximumChainedReferences {
            get {
                return ResourceManager.GetString("MaximumChainedReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum interface dependencies for a constructor ähnelt.
        /// </summary>
        internal static string MaximumConstructorDependencies {
            get {
                return ResourceManager.GetString("MaximumConstructorDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum expressions inside a condition ähnelt.
        /// </summary>
        internal static string MaximumExpressionsInsideACondition {
            get {
                return ResourceManager.GetString("MaximumExpressionsInsideACondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum level of nesting in a method ähnelt.
        /// </summary>
        internal static string MaximumLevelOfNestingInAMethod {
            get {
                return ResourceManager.GetString("MaximumLevelOfNestingInAMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum method declaration parameters ähnelt.
        /// </summary>
        internal static string MaximumMethodDeclarationParameters {
            get {
                return ResourceManager.GetString("MaximumMethodDeclarationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum methods per class ähnelt.
        /// </summary>
        internal static string MaximumMethodsPerClass {
            get {
                return ResourceManager.GetString("MaximumMethodsPerClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum statements per method ähnelt.
        /// </summary>
        internal static string MaximumStatementsPerMethod {
            get {
                return ResourceManager.GetString("MaximumStatementsPerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List of meaningless suffixes ähnelt.
        /// </summary>
        internal static string MeaninglessNameSuffixes {
            get {
                return ResourceManager.GetString("MeaninglessNameSuffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Separate items with commas ähnelt.
        /// </summary>
        internal static string MeaninglessNameSuffixesTooltip {
            get {
                return ResourceManager.GetString("MeaninglessNameSuffixesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum method name length ähnelt.
        /// </summary>
        internal static string MinimumMethodNameLength {
            get {
                return ResourceManager.GetString("MinimumMethodNameLength", resourceCulture);
            }
        }
    }
}
